package epc.spider.record;

import java.util.Collection;

import epc.metadataformat.data.DataAtomic;
import epc.metadataformat.data.DataGroup;
import epc.spider.record.storage.RecordStorage;

public class RecordStorageCreateUpdateSpy implements RecordStorage {

	public DataGroup createRecord;
	public String createId;
	public String createType;
	public DataGroup updateRecord;
	public String updateId;
	public String updateType;

	@Override
	public DataGroup read(String type, String id) {
		// TODO Auto-generated method stub
		if (type.equals("recordType") && id.equals("typeWithAutoGeneratedId")) {
			DataGroup group = DataGroup.withDataId("recordType");
			group.addChild(DataAtomic.withDataIdAndValue("newMetadataId", "placeNew"));
			group.addChild(DataAtomic.withDataIdAndValue("metadataId", "place"));
			group.addChild(DataAtomic.withDataIdAndValue("userSuppliedId", "false"));
			group.addChild(DataAtomic.withDataIdAndValue("abstract", "false"));
			
			return group;
		}
		if (type.equals("recordType") && id.equals("typeWithUserGeneratedId")) {
			DataGroup group = DataGroup.withDataId("recordType");
			group.addChild(DataAtomic.withDataIdAndValue("newMetadataId", "placeNew"));
			group.addChild(DataAtomic.withDataIdAndValue("metadataId", "place"));
			group.addChild(DataAtomic.withDataIdAndValue("userSuppliedId", "true"));
			group.addChild(DataAtomic.withDataIdAndValue("abstract", "false"));
			return group;
		}
		return null;
	}

	@Override
	public void create(String type, String id, DataGroup record) {
		createType = type;
		createId = id;
		createRecord = record;
	}

	@Override
	public void deleteByTypeAndId(String type, String id) {
		// TODO Auto-generated method stub

	}

	@Override
	public void update(String type, String id, DataGroup record) {
		// TODO Auto-generated method stub
		updateType = type;
		updateId = id;
		updateRecord = record;
	}

	@Override
	public Collection<DataGroup> readList(String type) {
		// TODO Auto-generated method stub
		return null;
	}

}
